# Generated by Django 3.2.5 on 2021-11-23 19:23

from django.db import migrations, models
import stock.models.stock_model


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="price_52_week_high",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="price_52_week_low",
        ),
        migrations.AddField(
            model_name="stock",
            name="ratios",
            field=models.JSONField(
                default=stock.models.stock_model.default_ratios_dict
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="sector",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
