# Generated by Django 3.2.5 on 2021-12-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_auto_20211124_0053"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="high",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="low",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="ltp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="prev_ltp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
