# Generated by Django 3.2.10 on 2022-01-18 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_auto_20211213_1450"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockFinancial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[("annual", "Annual"), ("quarterly", "Quarterly")],
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
                ("fiscal_date", models.DateField(db_index=True)),
                ("data", models.JSONField()),
                (
                    "statement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("balancesheet", "Balance Sheet"),
                            ("income", "Income Statement"),
                            ("cashflow", "Cash Flow"),
                        ],
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="financials",
                        to="stock.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "StockFinancial",
                "verbose_name_plural": "Stock Financials",
                "db_table": "Stock_Financial",
                "unique_together": {("statement", "fiscal_date", "period")},
            },
        ),
    ]
