# Generated by Django 3.2.10 on 2022-01-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_stockfinancial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockfinancial",
            unique_together={("statement", "fiscal_date", "period", "stock")},
        ),
    ]
