# Generated by Django 3.2.10 on 2022-01-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_alter_stockfinancial_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="details",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="statistics",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
