# Generated by Django 3.2.5 on 2021-11-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("smallcase", "0001_initial"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(db_index=True, max_length=512, unique=True)),
                ("description", models.TextField()),
                (
                    "api_source",
                    models.CharField(
                        choices=[
                            ("News API", "News Api"),
                            ("Smallcase", "Smallcase"),
                            ("Google Rss", "Google Rss"),
                            ("None", "None"),
                        ],
                        default="None",
                        max_length=16,
                    ),
                ),
                ("source_name", models.CharField(max_length=64)),
                (
                    "source_id",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("url", models.URLField(max_length=512)),
                ("image_url", models.URLField(blank=True, max_length=356, null=True)),
                ("published_at", models.DateTimeField()),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("smallcases", models.ManyToManyField(to="smallcase.Smallcase")),
                ("tickers", models.ManyToManyField(to="stock.Stock")),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "db_table": "News",
                "managed": True,
            },
        ),
    ]
