# Generated by Django 3.2.5 on 2021-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="source_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
