# Generated by Django 3.2.3 on 2021-05-25 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[("Bullish", "Bullish"), ("Bearish", "Bearish")],
                        max_length=16,
                    ),
                ),
                ("content", models.CharField(max_length=512)),
                ("signal_end_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "Post",
                "managed": True,
            },
        ),
    ]
