# Generated by Django 3.2.5 on 2021-11-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="source",
            field=models.JSONField(default={"symbol": "INFY", "ticker_type": "Stock"}),
            preserve_default=False,
        ),
    ]
