# Generated by Django 3.2.5 on 2021-11-29 05:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_post_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("object_id", "created_by_user_id")},
        ),
    ]
