# Generated by Django 3.2.3 on 2021-05-25 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_stock_created_by_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_post_created_by_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostStockMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poststockmention_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="posts",
                        to="post.post",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="stocks",
                        to="stock.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post_StockMention",
                "verbose_name_plural": "Post_StockMentions",
                "db_table": "Post_StockMention",
                "managed": True,
            },
        ),
    ]
