# Generated by Django 3.2.5 on 2021-12-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_auto_20211214_1703"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="reward",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
