# Generated by Django 3.2.5 on 2021-12-31 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("LikePost", "Like Post"),
                            ("LikeComment", "Like Comment"),
                            ("NewPost", "New Post"),
                            ("CommentOnPost", "Comment On Post"),
                            ("MentionOnPost", "Mention On Post"),
                            ("FollowUser", "Follow User"),
                            ("UserSuccessRateChange", "User Success Rate Change"),
                            ("UserKarmaChange", "User Karma Change"),
                            ("UserLeaderboard", "User Leaderboard"),
                            ("PostTargetHit", "Post Target Hit"),
                            ("PostTargetMiss", "Post Target Miss"),
                        ],
                        max_length=32,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "Notification",
                "managed": True,
            },
        ),
    ]
