# Generated by Django 3.2.10 on 2022-01-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("LikePost", "Like Post"),
                    ("LikeComment", "Like Comment"),
                    ("NewPost", "New Post"),
                    ("CommentOnPost", "Comment On Post"),
                    ("MentionOnPost", "Mention On Post"),
                    ("FollowUser", "Follow User"),
                    ("UserSuccessRateChange", "User Success Rate Change"),
                    ("UserKarmaChange", "User Karma Change"),
                    ("UserLeaderboard", "User Leaderboard"),
                    ("LeaderboardResults", "Leaderboard Results"),
                    ("PostTargetHit", "Post Target Hit"),
                    ("PostTargetMiss", "Post Target Miss"),
                ],
                max_length=32,
            ),
        ),
    ]
