# Generated by Django 3.2.5 on 2021-12-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_userholding_holdings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="success_rate",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
